[package]
name = "ruast_proc_macro_example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ruast = { version = "0.0.16", features = ["tokenize"] }
syn = "1.0.109"

[lib]
proc-macro = true
